### ISSUE TITLE
sylvester equation solver with non-square C

### ISSUE THREAD

**Issue by emauryg** [kyoustat/maotai#1]
Thank you for developing maotai with so many helpful functions. I was wondering if it would be possible to remove the check for C to be square in the sylvester function. To the best of my understanding C does not need to be a square matrix is A and B are square matrices with different dimensions.

**Comment by kisungyou** [comment]
Hi @emauryg. As the documentation states, currently it's merely a wrapper of sylvester equation solver in RcppArmadillo which supports square-type matrices only at this stage. I've looked up whether other generic solvers that use kinds of Bartels–Stewart algorithm in R ecosystem - I failed. Although I plan to include such features in the future, I'm sorry I can't help at this moment.

**Comment by emauryg** [comment]
No worries! I have implemented a solution using the Bartels-Stewart Algorithm in R to solve this issue. Thank you.
